from enum import Enum

class EventType(Enum):
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_ARCHIVED = "PROJECT_ARCHIVED"
    MEMBER_ADDED = "MEMBER_ADDED"
    MEMBER_REMOVED = "MEMBER_REMOVED"
    REVIEWER_ADDED = "REVIEWER_ADDED"
    COMMENT_ADDED = "COMMENT_ADDED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_DELETED = "TASK_DELETED"
    COMMENT_DECOMPOSED = "COMMENT_DECOMPOSED"
    ATTACHMENT_UPLOADED = "ATTACHMENT_UPLOADED"
    TASK_COMMENT_ADDED = "TASK_COMMENT_ADDED"

    @classmethod
    def events(cls) -> list[str]:
        return [item.value for item in cls]