"""add soft delete columns

Revision ID: ebb467e402db
Revises: 665efdc46040
Create Date: 2026-04-25 16:25:18.666914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb467e402db'
down_revision: Union[str, Sequence[str], None] = '665efdc46040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_reviewers_deleted_at'), 'reviewers', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewers_deleted_at'), table_name='reviewers')
    op.drop_column('reviewers', 'deleted_at')
    # ### end Alembic commands ###
